"""Cross-SDK interop: Python reads .cv files produced by other SDKs.

The fixture file is generated by the JS SDK demo
(packages/sdk-js/examples/build-jane-doe.ts). The test is skipped if the
fixture is missing, so this test passes in fresh checkouts and tightens
gradually as the interop corpus grows.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from cvfile import extract, extract_html, extract_markdown, inspect, is_cv_file

REPO_ROOT = Path(__file__).resolve().parents[3]
JS_FIXTURE = REPO_ROOT / "packages" / "sdk-js" / "examples" / "out" / "jane-doe.cv"
JS_MD_SOURCE = REPO_ROOT / "packages" / "sdk-js" / "examples" / "jane-doe.md"
JS_HTML_SOURCE = REPO_ROOT / "packages" / "sdk-js" / "examples" / "jane-doe.html"


@pytest.fixture
def js_fixture_bytes() -> bytes:
    if not JS_FIXTURE.exists():
        pytest.skip(
            f"JS fixture missing at {JS_FIXTURE}; "
            "run `pnpm --filter @cvfile/sdk` then `npx tsx examples/build-jane-doe.ts`"
        )
    return JS_FIXTURE.read_bytes()


def test_python_recognises_js_produced_cv(js_fixture_bytes: bytes) -> None:
    assert is_cv_file(js_fixture_bytes) is True


def test_python_inspects_js_metadata(js_fixture_bytes: bytes) -> None:
    meta = inspect(js_fixture_bytes)
    assert meta.version == "1.0"
    assert meta.primary_language == "en"
    assert meta.primary_payload == "resume.md"
    assert meta.generator is not None and "cv-examples" in meta.generator
    assert len(meta.integrity) >= 1
    assert all(i.algorithm in {"sha-256", "sha256"} for i in meta.integrity)


def test_python_extracts_js_markdown_byte_identical(js_fixture_bytes: bytes) -> None:
    src = JS_MD_SOURCE.read_text(encoding="utf-8")
    md = extract_markdown(js_fixture_bytes)
    assert md == src


def test_python_extracts_js_html_byte_identical(js_fixture_bytes: bytes) -> None:
    if not JS_HTML_SOURCE.exists():
        pytest.skip("JS HTML source missing")
    src = JS_HTML_SOURCE.read_text(encoding="utf-8")
    html = extract_html(js_fixture_bytes)
    assert html == src


def test_python_extracts_all_js_payloads(js_fixture_bytes: bytes) -> None:
    file = extract(js_fixture_bytes)
    names = sorted(p.name for p in file.payloads)
    # JS demo embeds md, html, json, embeddings.cbor
    assert "resume.md" in names
    assert "resume.html" in names
    assert "resume.json" in names
    assert "embeddings.cbor" in names
